### PR TITLE
add workflow for Fastify Integration testing

### PR DESCRIPTION
**Pull request by Uzlopak**
This PR introduces a workflow, which should help us to detect regressions and incompatibilities in fastify. This is relevant especially for the PR #252, where tests of light-my-requests pass, but testing in fastify breaks.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
@Fdawgs 

Maybe a workflow which should be generalized in the plugins-ci.yml for dependencies which are integral part of <s>china</s> fastify?

**Review by jsumners — COMMENTED** [review]
How is this triggered from `fastify/fastify` changes?

**Comment by Uzlopak** [comment]
@jsumners 

It is not about being triggered when fastify core gets changes. Every change on fastify core results in loading latest version of light-my-request. 
It is about ensuring that changes in light-my-request are not breaking fastify. E.g. the changes in #252 by @sirenkovladd are passing the unit tests but are breaking fastify. If I didnt test it like I did in the workflow, I would not know that it broke fastify. Maybe approved the PR and then after release, realize that there is an issue.
This workflow ensures, that we see before merging, that there is something wrong.

**Comment by Uzlopak** [comment]
moved the workflow to fastify/workflows.

Dont merge this PR

**Comment by Uzlopak** [comment]
@Fdawgs 
@jsumners 
PTAL

**Review by Fdawgs — APPROVED** [review]

**Pull request merged**
