### PR TITLE
Add json() handler for Response

### PR DESCRIPTION
**Pull request by fralonra**
Add `json()` handler for Response.
And I'm wondering if error thrown by `JSON.stringify` shoud be handled.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by fralonra** [comment]
> I meant something different. I would like to `json()` in
> 
> https://github.com/fastify/light-my-request/blob/502878ae4fd45be41b4cf690baf212e0a41f38fc/lib/response.js#L92
> 
> . In the response object we get from `light-my-request`.
> Sorry for the confusion!

So you meant a handler that parses the JSON payload of server response?

**Comment by mcollina** [comment]
Supporting something like this would be extremely nice:

```js
const http = require('http')
const inject = require('light-my-request')

const dispatch = function (req, res) {
  const reply = 'Hello World'
  res.writeHead(200, { 'Content-Type': 'text/plain', 'Content-Length': reply.length })
  res.end(reply)
}

const server = http.createServer(dispatch)

inject(dispatch, { method: 'get', url: '/' }, (err, res) => {
  console.log(res.json()) // validates that the content-type is set to JSON and parses it, otherwise it throws
})
```

**Comment by mcollina** [comment]
Something similar to what `fetch` provides

**Comment by fralonra** [comment]
I see. Close then.

**Pull request closed without merging**
