### PR TITLE
fix: properly handle Express.js send payload

### PR DESCRIPTION
**Pull request by L2jLiga**
Took test from #155 
Also reverted changes in `response.js` made in #154

~`tsd` tests seems to fail on master too~ fixed in #222 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm, wow!

**Comment by SimenB** [comment]
Oh, sweet! I opened up #222 for the type error - would be great to land it then rebase this PR to verify CI is happy (the unit tests passed, so I assume so 🙂)

**Review by Uzlopak — APPROVED** [review]

**Comment by SimenB** [comment]
@L2jLiga could you rebase?

**Comment by L2jLiga** [comment]
Yep, just pushed

**Review by SimenB — APPROVED** [review]
🎉

**Comment by SimenB** [comment]
Hmm, updating in my project, and `headers` are now missing.

image

I'm about to call it a week, but I'll do some more digging Monday (or this weekend if I'm bored)

**Comment by SimenB** [comment]
See https://github.com/fastify/fastify-express/issues/47#issuecomment-1242671020 for a reproduction

**Pull request merged**
