### PR TITLE
Only http.METHODS

### PR DESCRIPTION
**Pull request by allevo**
From https://github.com/fastify/fastify/pull/883#issuecomment-382182010

### CODE REVIEW

**Comment by allevo** [comment]
Truly the method http is case-sensitive by RFC

https://tools.ietf.org/html/rfc2616#section-5.1.1

This is a bugfix. Anyway if you want, I change in order to allow both kind of cases.

**Comment by delvedor** [comment]
I know, in fact as you can see we uppercase it internally.
Unfortunately this bugfix is also a breaking change, so it is better to keep both uppercase and lowercase.

**Comment by allevo** [comment]
I have added a test for the lower case HTTP method. So that behaviour is tracked

**Comment by allevo** [comment]
I've no rights for merging this

**Pull request merged**
