### PR TITLE
Add missing type for Response.raw.req

### PR DESCRIPTION
**Pull request by sadams**
It's added here: https://github.com/fastify/light-my-request/blob/master/lib/response.js#L40

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)
  - Note: couldn't find anything about commit message requirements

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please add a unit test?

**Comment by sadams** [comment]
@mcollina i couldn't see any other explicit tests for anything similar (e.g. the raw.res): https://github.com/fastify/light-my-request/blob/master/test/index.test-d.ts 
If you can point me to something similar or give me an example of how to go about i would be happy to do it.

**Comment by mcollina** [comment]
You should add another assertion similar to https://github.com/fastify/light-my-request/blob/634baa9b637ab1b893bd84ebdf2d2d74788ab2e2/test/index.test-d.ts#L21

**Comment by mcollina** [comment]
@Ethan-Arrowood @Eomm can you please take a look?

**Pull request merged**
